-- MySQL Script generated by MySQL Workbench
-- Sun Oct  9 13:24:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cruise
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cruise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cruise` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cruise` ;

-- -----------------------------------------------------
-- Table `cruise`.`cabin_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`cabin_status` (
  `cabin_status_id` INT NOT NULL AUTO_INCREMENT,
  `cabin_status_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cabin_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`cabin_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`cabin_types` (
  `cabin_type_id` INT NOT NULL AUTO_INCREMENT,
  `cabin_type_name` VARCHAR(255) NOT NULL,
  `number_of_beds` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`cabin_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`ships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`ships` (
  `ship_id` INT NOT NULL AUTO_INCREMENT,
  `ship_name` VARCHAR(255) NOT NULL,
  `cruise_id` INT NOT NULL,
  `passengers` INT NOT NULL,
  `number_of_staff` INT NOT NULL,
  PRIMARY KEY (`ship_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`cabins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`cabins` (
  `cabin_id` INT NOT NULL AUTO_INCREMENT,
  `cabin_type_id` INT NOT NULL,
  `cabin_status_id` INT NOT NULL,
  `ship_id` INT NOT NULL,
  PRIMARY KEY (`cabin_id`),
  INDEX `ship_id` (`ship_id` ASC) VISIBLE,
  INDEX `cabin_status_id` (`cabin_status_id` ASC) VISIBLE,
  INDEX `cabin_type_id` (`cabin_type_id` ASC) VISIBLE,
  CONSTRAINT `cabins_ibfk_1`
    FOREIGN KEY (`ship_id`)
    REFERENCES `cruise`.`ships` (`ship_id`)
    ON DELETE CASCADE,
  CONSTRAINT `cabins_ibfk_2`
    FOREIGN KEY (`cabin_status_id`)
    REFERENCES `cruise`.`cabin_status` (`cabin_status_id`)
    ON DELETE CASCADE,
  CONSTRAINT `cabins_ibfk_3`
    FOREIGN KEY (`cabin_type_id`)
    REFERENCES `cruise`.`cabin_types` (`cabin_type_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`cruise_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`cruise_statuses` (
  `cruise_status_id` INT NOT NULL AUTO_INCREMENT,
  `cruise_status_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cruise_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`routes` (
  `route_id` INT NOT NULL AUTO_INCREMENT,
  `route_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`route_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`cruises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`cruises` (
  `cruise_id` INT NOT NULL AUTO_INCREMENT,
  `cruise_name` VARCHAR(255) NOT NULL,
  `route_id` INT NOT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NOT NULL,
  `cruise_status_id` INT NOT NULL,
  `ship_id` INT NOT NULL,
  PRIMARY KEY (`cruise_id`),
  INDEX `route_id` (`route_id` ASC) VISIBLE,
  INDEX `cruise_status_id` (`cruise_status_id` ASC) VISIBLE,
  CONSTRAINT `cruises_ibfk_1`
    FOREIGN KEY (`route_id`)
    REFERENCES `cruise`.`routes` (`route_id`),
  CONSTRAINT `cruises_ibfk_2`
    FOREIGN KEY (`cruise_status_id`)
    REFERENCES `cruise`.`cruise_statuses` (`cruise_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`order_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`order_statuses` (
  `order_status_id` INT NOT NULL AUTO_INCREMENT,
  `order_status_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`order_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `cruise`.`role` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  `order_status_id` INT NOT NULL,
  `cruise_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `order_status_id` (`order_status_id` ASC) VISIBLE,
  INDEX `cruise_id` (`cruise_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cruise`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `cruise`.`order_statuses` (`order_status_id`)
    ON DELETE CASCADE,
  CONSTRAINT `orders_ibfk_3`
    FOREIGN KEY (`cruise_id`)
    REFERENCES `cruise`.`cruises` (`cruise_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`orders_cabins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`orders_cabins` (
  `order_id` INT NULL DEFAULT NULL,
  `cabin_id` INT NULL DEFAULT NULL,
  `cabins_cabin_id` INT NOT NULL,
  `orders_order_id` INT NOT NULL,
  INDEX `fk_orders_cabins_cabins1_idx` (`cabins_cabin_id` ASC) VISIBLE,
  INDEX `fk_orders_cabins_orders1_idx` (`orders_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_cabins_cabins1`
    FOREIGN KEY (`cabins_cabin_id`)
    REFERENCES `cruise`.`cabins` (`cabin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_cabins_orders1`
    FOREIGN KEY (`orders_order_id`)
    REFERENCES `cruise`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `payment_date` DATE NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `payments_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `cruise`.`orders` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`ports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`ports` (
  `port_id` INT NOT NULL AUTO_INCREMENT,
  `port_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`port_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cruise`.`route_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruise`.`route_points` (
  `route_point_id` INT NOT NULL AUTO_INCREMENT,
  `route_id` INT NOT NULL,
  `day_number` INT NOT NULL,
  `port_id` INT NOT NULL,
  PRIMARY KEY (`route_point_id`),
  INDEX `route_id` (`route_id` ASC) VISIBLE,
  INDEX `port_id` (`port_id` ASC) VISIBLE,
  CONSTRAINT `route_points_ibfk_1`
    FOREIGN KEY (`route_id`)
    REFERENCES `cruise`.`routes` (`route_id`)
    ON DELETE CASCADE,
  CONSTRAINT `route_points_ibfk_2`
    FOREIGN KEY (`port_id`)
    REFERENCES `cruise`.`ports` (`port_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
