package com.vladnickgo.Project.validator;

public class ValidatorErrorMessage {
    public static final String EMAIL_ERROR_MESSAGE = "Email is not valid";
    public static final String PASSWORD_ERROR_MESSAGE = "Password is not valid";
    public static final String CONFIRMATION_PASSWORD_ERROR_MESSAGE = "ConfirmationPassword is not valid";
    public static final String USER_IS_NULL_MESSAGE = "User is null";
    public static final String FIRST_NAME_ERROR_MESSAGE = "First name is not valid";
    public static final String LAST_NAME_ERROR_MESSAGE = "Last name is not valid";
    public static final String USER_ALREADY_EXIST_ERROR_MESSAGE = "User with email <strong>%s</strong> is already registered";
    public static final String NOT_AVAILABLE_PAGE = "The page is not available";
    public static final String USER_WITH_EMAIL_NOT_FOUND = "User with email <strong>%s</strong> not found";
    public static final String NOT_CORRECT_DATE_START = "Not correct date start";
    public static final String NOT_CORRECT_DATE_END = "Not correct date end";
    public static final String NOT_CORRECT_ORDER_DATE = "Not correct order date";
    public static final String DATE_START_MORE_OR_EQUAL_THAN_DATE_END = "Date start more or equal than date end";
    public static final String BOOKING_DATE_MORE_THAN_DATE_CHECK_IN = "Booking date more than date checkIn";
    public static final String ORDER_DATE_MORE_THAN_DATE_CHECK_IN = "Order date more than date checkIn";
    public static final String DATA_ABOUT_ROOM_IS_ABSENT = "Data about room is absent";
    public static final String USER_DATA_IS_ABSENT = "Data about user is absent";
    public static final String NOT_VALID_NUMBER_OF_PERSONS = "Not valid number of persons";
    public static final String USERS_ORDER_IS_NULL = "Users order is null";
    public static final String USER_IS_NULL = "User is null";
    public static final String NUMBER_OF_PERSONS_IS_NULL = "Number of persons is null";
    public static final String ORDER_STATUS_IS_NULL = "Order status is null";
    public static final String NOT_CORRECT_PAYMENT_DATE = "Not correct payment date";
    public static final String NOT_CORRECT_AMOUNT_VALUE = "Not correct amount value";
    public static final String EMPTY_DATE_START = "Empty date start";
    public static final String EMPTY_DATE_END = "Empty date end";
    public static final String CRUISE_IS_NULL_MESSAGE = "Cruise is null";
    public static final String EMPTY_CRUISE_NAME = "Empty cruise name";
    public static final String EMPTY_ROUTE_NAME = "Empty route name";
    public static final String EMPTY_CRUISE_STATUS_NAME = "Empty cruise status name";
    public static final String CRUISE_NOT_FOUND = "Cruise not found";
    public static final String CABIN_NOT_FOUND = "Cabin not found";
    public static final String ID_CARD_FILE_NAME_IS_NOT_VALID = "idCard file name is not valid";
    public static final String CARD_NUMBER_IS_NOT_VALID = "Card number is not valid";
    public static final String CVV_NUMBER_IS_NOT_VALID = "CVV number is not valid";
    public static final String USER_ID_IS_NULL = "userId is null";
    public static final String CABIN_STATUS_ID_IS_NULL = "cabinStatusId is null";
    public static final String CRUISE_ID_IS_NULL = "cruiseId is null";
    public static final String AMOUNT_VALUE_IS_NULL = "Amount value is null";
    public static final String SHIP_IS_NULL_MESSAGE = "Ship is null";
    public static final String SHIP_NAME_IS_EMPTY = "Ship name is empty";
    public static final String SHIP_IMAGE_IS_EMPTY = "Ship image is empty";
}
